"""default for donations

Revision ID: 534514b02bb3
Revises: 815c1cf34f3c
Create Date: 2023-05-14 21:33:43.895645

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '534514b02bb3'
down_revision = '815c1cf34f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
