"""empty message

Revision ID: 6c466a855b17
Revises: 21ec62d61abb
Create Date: 2023-05-14 20:53:50.042793

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6c466a855b17'
down_revision = '21ec62d61abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
