"""create abstract model

Revision ID: 8785fd0780e0
Revises: 534514b02bb3
Create Date: 2023-05-15 12:21:00.408415

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8785fd0780e0'
down_revision = '534514b02bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
